# Generated by Django 4.1.6 on 2023-04-05 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tabulation', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SineData',
        ),
    ]
